services:
  compose:
    image: sibr_viewers
    volumes:
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: "host"
    environment:
      - DISPLAY=192.168.1.117:0.0
    command: /usr/local/bin/entrypoint.sh